### ISSUE TITLE
Flakey tests

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk_publishing_components#2524]
## Problem
We have a bunch of flakey tests in the components gem. A flakey test in this instance is a test that isn't related to a change you made, fails intermittently and passes upon a re-run.

This issue is just a means to record these dodgy test for now so that we can try to understand why this is happening.

**Comment by owenatgov** [comment]
## Contextual navigation

```
Contextual navigation The page has a topic
     Failure/Error: expect(page).to have_link(topic_item["title"])
       expected `#<Capybara::Session>.has_link?("Oil and gas")` to be truthy, got false
     # ./spec/features/contextual_navigation_spec.rb:485:in `block in then_i_see_the_topic_breadcrumb'
     # /var/lib/jenkins/bundles/ruby/2.6.0/gems/capybara-3.36.0/lib/capybara/session.rb:363:in `within'
     # /var/lib/jenkins/bundles/ruby/2.6.0/gems/capybara-3.36.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # /var/lib/jenkins/bundles/ruby/2.6.0/gems/capybara-3.36.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/features/contextual_navigation_spec.rb:483:in `then_i_see_the_topic_breadcrumb'
     # ./spec/features/contextual_navigation_spec.rb:74:in `block (2 levels) in <top (required)>'
```

```
rspec ./spec/features/contextual_navigation_spec.rb:71 # Contextual navigation The page has a topic
```

**Comment by andysellick** [comment]
Just found some in `static` (I know this isn't the right repo, but it might relate to code in the gem and grouping them together might be helpful for reference). Fails roughly every other run.

```
Surveys > Event handlers > for an email survey > once the email form is opened > records an event when clicking 'no thanks'
Expected spy trackEvent to have been called with:
  [ 'email-survey', 'email_survey_cancel', 'Email survey cancelled' ]
but actual calls were:
  [ 'email-survey', 'banner_no_thanks', 'No thanks clicked' ].

Call 0:
  Expected $[1] = 'banner_no_thanks' to equal 'email_survey_cancel'.
  Expected $[2] = 'No thanks clicked' to equal 'Email survey cancelled'.

Surveys > Event handlers > for an email survey > records an event when clicking 'no thanks'
Expected spy trackEvent to have been called with:
  [ 'email-survey', 'banner_no_thanks', 'No thanks clicked' ]
but actual calls were:
  [ 'email-survey', 'email_survey_cancel', 'Email survey cancelled' ].

Call 0:
  Expected $[1] = 'email_survey_cancel' to equal 'banner_no_thanks'.
  Expected $[2] = 'Email survey cancelled' to equal 'No thanks clicked'.
```

**Comment by owenatgov** [comment]
Just had the contextual nav test fail again, making 3 instances recorded https://ci.integration.publishing.service.gov.uk/job/govuk_publishing_components/job/big-number-margin-bottom/4/console

```
  1) Contextual navigation The page has many topics
     Failure/Error: expect(page).to have_link(topic_item["title"])
       expected `#<Capybara::Session>.has_link?("Oil and gas")` to be truthy, got false
     # ./spec/features/contextual_navigation_spec.rb:484:in `block in then_i_see_the_topic_breadcrumb'
     # /var/lib/jenkins/bundles/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/session.rb:363:in `within'
     # /var/lib/jenkins/bundles/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/dsl.rb:53:in `call'
     # /var/lib/jenkins/bundles/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/dsl.rb:53:in `within_element'
     # /var/lib/jenkins/bundles/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/features/contextual_navigation_spec.rb:482:in `then_i_see_the_topic_breadcrumb'
     # ./spec/features/contextual_navigation_spec.rb:80:in `block (2 levels) in <top (required)>'
```

I'm going to raise this at the next govuk frontenders catchup and propose we either change this issue to target the contextual nav tests or create a new issue around this.
